name: Trash-Talks-alive🎉
on:
  schedule:
    # run once per day (you can change)
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST
        env:
          SUPABASE_URL: https://esbfcqbulugvfeosqzrd.supabase.co
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzYmZjcWJ1bHVndmZlb3NxenJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTU3MjQsImV4cCI6MjA2NjQ5MTcyNH0.nzKkVWuUoQC3rLlcER4ov_7P8gqwbxQLzBCQk9AQu9A
        run: |
          # simple request to list a lightweight table (or to the root URL)
          curl -sSf -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzYmZjcWJ1bHVndmZlb3NxenJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTU3MjQsImV4cCI6MjA2NjQ5MTcyNH0.nzKkVWuUoQC3rLlcER4ov_7P8gqwbxQLzBCQk9AQu9A" \
            -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzYmZjcWJ1bHVndmZlb3NxenJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MTU3MjQsImV4cCI6MjA2NjQ5MTcyNH0.nzKkVWuUoQC3rLlcER4ov_7P8gqwbxQLzBCQk9AQu9A" \
            "https://esbfcqbulugvfeosqzrd.supabase.co/rest/v1/your_small_table?select=id&limit=1" || \
          curl -sSf "https://esbfcqbulugvfeosqzrd.supabase.co" || exit 0

